### ISSUE TITLE
Renaming sokol-samples crashes fips

### ISSUE THREAD

**Issue by thoughton** [floooh/sokol-samples#10]
Hi,

After cloning this repo, if the repo directory (sokol-samples) is renamed to something else (eg. "sokol"), and then that directory is entered and any `./fips` command is run, fips will clone/update itself but then python will get stuck and crash with a `RuntimeError: maximum recursion depth exceeded`.

(Everything works fine if I don't rename the directory.)

Thanks!

**Comment by thoughton** [comment]
Ohhhh hang on, is this just because I'm renaming it "sokol" but that directory name is actually needed for sokol-related files...?

If so, please accept my apologies and feel free to close this!

**Comment by floooh** [comment]
Yeah, sokol is the directory name of a required dependency (https://github.com/floooh/sokol), so a dependency on itself was created. For simple cases like this it could be detected and a better error message printed, but I guess for indirect cases it would be harder to detect.
