### ISSUE TITLE
Sapp targets on macos failed to load resources

### ISSUE THREAD

**Issue by pixelpicosean** [floooh/sokol-samples#100]
It seems like sokol_fetch path is not properly set on macos for running apps by clicking instead of commandline.

**Comment by floooh** [comment]
Yes this is a known issue with the samples. sokol_fetch.h doesn't have any special handling for absolute vs relative paths, it basically expects that the provided path "does the right thing" (e.g. is an absolute path, or relative to the current cwd).

For iOS I've created this special fix which converts the relative path from the samples into an absolute path:

https://github.com/floooh/sokol-samples/blob/1fe2ac2b0d4c1295c13a427b81e18eb8754ed40a/libs/util/fileutil.m#L6-L11

But for other platforms such a fix hasn't been implemented so far.

**Comment by nobe4** [comment]
FWIW, I was successful in doing something like that for a macOS build.

```c
#include "util.h"
#include <stdio.h>
#include <libgen.h>

#if defined(__APPLE__)

#include <mach-o/dyld.h>
#include <limits.h>

const char* get_path(const char* filename, char* buf, size_t buf_size) {
  char osx_path [PATH_MAX];
  uint32_t osx_path_size = PATH_MAX;

  if(!_NSGetExecutablePath(osx_path, &osx_path_size)) {
    snprintf(buf, buf_size, "%s/%s", dirname(osx_path), filename);
    return buf;
  }

  return 0;
}

#else

const char* get_path(const char* filename, char* buf, size_t buf_size) {
    snprintf(buf, buf_size, "%s", filename);
    return buf;
}

#endif
```

Used like so:

```c
char buf [1000];
sfetch_send(&(sfetch_request_t){ .path = get_path("textures/tilemap.png", buf, 1000),
                                 // ... 
                               });
```

And I had to copy the file into the `.app` folder with:

```yaml
//assets.yaml
---
options:
  macos:
      dst_dir: <app_name>.app/Contents/MacOS
files: ["picture.png"]
```

and copy step in my cmake file:

```cmake
fipsutil_copy(assets.yml)
```

### Limitations

- This hasn't been extensively tested, here be 🐉 
- I'm not a C expert, so I've fixed the buffer size to `1000`, there must be a better way.
- In the assets.yaml file, the app name is fixed, which is not ideal. Upon looking at https://github.com/fips-libs/fips-utils/blob/master/fips-files/generators/copy.py it should be possible to inject the `app_name` at runtime. I'll try to see if I can make a PR over there for this.

**Comment by floooh** [comment]
Thanks! I'll see if I can find some time in the next few days to add this (or a similar fix) to the helper function in fileutil.m

**Comment by floooh** [comment]
Erm ok, "next few days" was a bit optimistic, but this is fixed now. On macOS, the asset files are copied into the app bundle into the Contents/Resources directory (I had added a similar fix for iOS earlier, just that the iOS 'resource path' seems to be directly in the app bundle root directory).
