### ISSUE TITLE
How to build without a build system.. with 3rd party libs

### ISSUE THREAD

**Issue by blazer2k1** [floooh/sokol-samples#115]
Building the nuklear sample was a breeze, but not the case with samples requiring ozzanim and imgui. I have not tested the others with required libs so far.

Also, imgui source is not included in the samples libs folder.

**Comment by floooh** [comment]
Yeah, this all gets tricky quickly with the non-trivial samples and would require a lot more documentation how to setup the external dependencies and so on. TL;DR: this would be out of scope for the readme.

**Comment by blazer2k1** [comment]
I see. I'm just curious to try the ozzanim example and it's just 3 files, any tips in building this dependency to work with sokol?

I just tried a library build (compile to .obj and then ar rcs) of ozzanim and I get link errors.

**Comment by floooh** [comment]
There's a separate ozzutil library here, did you integrate that too?

https://github.com/floooh/sokol-samples/tree/master/libs/ozzutil

Otherwise: what linker errors are you seeing?

**Comment by blazer2k1** [comment]
Yes, that's the one I'm trying to build. I don't have python installed yet and just expected CMake to work without that fips thing which is new to me.

Still having a no build option for most of the demos are very nice, given that the actual project is focused around being minimalistic. I just wish it would also be applicable to all examples.
