### ISSUE TITLE
running build on any config results in cmake error looking for default directory which doesn't exist

### ISSUE THREAD

**Issue by samwalls** [floooh/sokol-samples#130]
Hi, I've been trying to build the sokol samples using the fips steps specified in the README, and I can't seem to make any of the build configs work. Is there something obvious I'm missing? I'm familiar with cmake, but I'm not sure where this 'default' is defined, and why fips tries to do this.

setup steps prior to this:
- clone a fresh repository at `3e746d86cd87f634f4f7793c2e8d0ef71a2067ca`
- run `python fips set config sapp-win64-vstudio-debug`

then running `python fips build` I see this:

```
...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 54 (delta 18), reused 48 (delta 13), pack-reused 0
Receiving objects: 100% (54/54), 9.31 KiB | 501.00 KiB/s, done.
Resolving deltas: 100% (18/18), done.
=== building: sapp-win64-vstudio-debug
=== generating: sapp-win64-vstudio-debug
config file: <my-directory>/sokol-samples/fips-files/configs/sapp-win64-vstudio-debug.yml
CMake Error: The source directory "<my-directory>/scratch/sokol-samples/default" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[ERROR] Failed to generate 'sapp-win64-vstudio-debug' of project 'sokol-samples'
```

Versions:
- cmake 3.12.3
- python 3.12.0
- ninja 1.11.1
- git 2.29.2.windows.3

Does anyone here know what's wrong?

**Comment by samwalls** [comment]
I've just noticed that CMakeUserPresets.json defines the minimum version as
```
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 21,
    "patch": 0
  },
```

I updated cmake past this and the build works now. The minimum cmake version in the README needs to be bumped to 3.21.x I'm guessing?

**Comment by floooh** [comment]
Ah thanks for the investigation, the cmake error message isn't very helpful unfortunately.

Yeah, the cmake presets stuff is fairly new, and requires a higher minimal cmake version than the actual CMakeLists.txt files, which is a bit unfortunate. I'll try to align all mentions of the minimal cmake version number to 3.21.

Thanks for letting me know!

**Comment by kochol** [comment]
Please add this error to fips troubleshooting page or show the error on fips diag tools command.
