### ISSUE TITLE
a couple fixes for triangle strip in primtypes-sapp

### ISSUE THREAD

**Issue by digitalsignalperson** [floooh/sokol-samples#146]
I was playing with this and found a couple bugs:
1. The last x-column was skipped
2. if NUM_X != NUM_Y then the indices are all mangled

e.g. for 1 here's a 4x4 in triangle list mode
![image](https://github.com/user-attachments/assets/b2408796-1aa5-442b-afa8-1840b5c4d95f)

and then switching to triangle strip see missing last x column
![image](https://github.com/user-attachments/assets/d74ac449-4645-4a94-a92f-c5603c92c03e)

and if you try e.g. NUM_X = 4, NUM_Y =5 
![image](https://github.com/user-attachments/assets/73b09153-c849-4e2c-90db-ea47712a10e5)

The following changes fix these:
- include one more x value in the inner loop
- multiply y by number of columns, not number of rows

```diff
-#define NUM_TRIANGLE_STRIP_INDICES ((NUM_X-1) * (NUM_Y-1) * 2 + (NUM_Y-1) * 2)
+#define NUM_TRIANGLE_STRIP_INDICES (NUM_X * (NUM_Y-1) * 2 + (NUM_Y-1) * 2)
```

in `setup_vertex_and_index_data()`
```diff
-            for (int x = 0; x < (NUM_X - 1); x++) {
-                i0 = x + y * NUM_Y;
+            for (int x = 0; x < NUM_X; x++) {
+                i0 = x + y * NUM_X;
```

**Comment by floooh** [comment]
Oops, yep. Thanks for the fix! I applied it in this commit: https://github.com/floooh/sokol-samples/commit/4905a5322e0925ff97e03f620e4d7664d697c487
