### ISSUE TITLE
Building sapp-android-ninja-debug in Windows 10

### ISSUE THREAD

**Issue by Ignitron** [floooh/sokol-samples#150]
When executing `fips build` after having configured fips with `fips set config sapp-android-ninja-debug` I get this error. No idea  if it is  a bug although but I also don't have more ideas on how to continue.
![image](https://github.com/user-attachments/assets/cc8060ca-bbfe-4474-a76d-6d6927661f66)
It seems there are a bunch of dependencies that previously passed the check:
![image](https://github.com/user-attachments/assets/392371f8-2647-4427-90b5-2eabb1c97fdf)
![image](https://github.com/user-attachments/assets/c6a96e74-e748-481b-8e3b-e864848c3d72)
![image](https://github.com/user-attachments/assets/839d8234-714c-470f-adbd-355ea065ae9d)
![image](https://github.com/user-attachments/assets/7fabb23f-d8e1-4e9f-8acf-32e264a8e716)
![image](https://github.com/user-attachments/assets/d0d995f4-4231-4ac3-8637-cf651c4b439b)
![image](https://github.com/user-attachments/assets/c22b3114-cfc1-4700-a7df-ced92f51930b)
![image](https://github.com/user-attachments/assets/99591207-540d-4a9f-b626-e9b86fbd5da5)
![image](https://github.com/user-attachments/assets/d94c4afc-d063-41a3-b2d0-9539861e1976)
![image](https://github.com/user-attachments/assets/631e886b-e566-49cc-8c38-e35ba6e2b8c8)
It is probably another check where it is failing but there is no error shown and don't know how to proceed...

**Comment by floooh** [comment]
Hmm, looks like there is no build config called `sapp-android-ninja-debug` anymore, only `sapp-android-make-debug` not sure when and why I removed that. Or if you have VSCode installed, you can also use `sapp-android-vscode-debug`, this uses Ninja instead of make as build tool.

In any case, you can run `fips list configs` to see a list of build configs, `fips diag configs` to check if all prerequisites are met, and `fips diag tools` to check if expected tools exist.

**Comment by floooh** [comment]
PS: Android development on Windows is a PITA though (for instance I currently get a error that no JDK is installed even though I have installed `openjdk8-redhat` installed via scoop. This stuff tends to break every couple of months.

**Comment by floooh** [comment]
PS: I just added those build configs back (`sapp-android-ninja-debug` and `sapp-android-ninja-release`), so the README should be correct again.

**Comment by Ignitron** [comment]
> PS: I just added those build configs back (`sapp-android-ninja-debug` and `sapp-android-ninja-release`), so the README should be correct again.
> 
> Tested on macOS (Linux should work too). On Windows the build complains that it can't find a JDK version 8 despite me having installed `openjdk8-redhat` via scoop. Don't know what's up with that, stuff tends to break every couple of months in Android land though, so not surprising.

You probably missing the JAVA_HOME and JDK_HOME environment variables.

**Comment by Ignitron** [comment]
Tested with the last version, this is the diag tools:
![image](https://github.com/user-attachments/assets/6416834f-d21e-4209-afe2-eecb5298e0fd)

And this is the new error when fips build:
![image](https://github.com/user-attachments/assets/bbda9398-7c80-422c-9fa2-86c2cbbba42d)

**Comment by floooh** [comment]
Looks like your sokol repository version needs to be updated. Try running:

```
fips update
```

**Comment by Ignitron** [comment]
Thanks for the tips. I did `fips update` and somehow now seems like not detecting the opengl headers?
[Build2.txt](https://github.com/user-attachments/files/16873754/Build2.txt)

**Comment by floooh** [comment]
Wrong build config ;)

You're trying to build `android-vscode-debug` now, but the correct one is `sapp-android-ninja-debug`.

The way the cmake files are written, when the 'sapp' part is missing, it will try to build the GLFW samples, and those don't work on Android.

**Comment by Ignitron** [comment]
True, I was trying anything after the last attempt and realized I would probably be happier with vscode cause I could do `fips open`.
So did a `fips clean`  and after the `fips build` finally got it running. Thank you so much!.
