### ISSUE TITLE
WebGPU builds cannot create buffer?

### ISSUE THREAD

**Issue by c1b** [floooh/sokol-samples#151]
[On MacOS]
* WebGPU examples on https://floooh.github.io/sokol-webgpu/ all work
* All examples work when built with Metal or WebGL2+WASM
* Build for WGPU succeeds

However, when running examples built with WebGPU:
*  In browser, all I can see is black screen
* dev tools indicate that buffers are failing to be created? 

From ./fips run triangle-sapp:

<img width="689" alt="image" src="https://github.com/user-attachments/assets/2cecbabe-a4e1-4709-8043-29f2bf44c1cf">

From ./fips run spine-layers-sapp:

<img width="694" alt="image" src="https://github.com/user-attachments/assets/038ac562-e549-496c-b39d-00ca07cf9d09">

(Pasted errors):
```
Vertex range (first: 0, count: 3) requires a larger buffer (84) than the bound buffer size (0) of the vertex buffer at slot 0 with stride 28.
 - While encoding [RenderPassEncoder (unlabeled)].Draw(3, 1, 0, 0).
```
```
Write range (bufferOffset: 0, size: 10856016) does not fit in [Buffer "sgl-vertex-buffer"] size (1835008).
 - While calling [Queue].WriteBuffer([Buffer "sgl-vertex-buffer"], (0 bytes), data, (10856016 bytes))
```

**Comment by floooh** [comment]
Hmm, could be a recent change in the Emscripten SDK WebGPU shim, or maybe a Chrome beta/canary/dev version?

Can you provide the following info?

- what Emscripten SDK used (you can check with './fips emsdk list' and look for smth like:

```
All recent (non-legacy) installable versions are:
         3.1.67    INSTALLED
```

- what browser and browser version is used when running `./fips run ...`

Thanks!

**Comment by floooh** [comment]
Ohhh... nevermind I can reproduce the problems...

I'm currently deep in sokol-shdc stuff, but will try to investigate as soon as possible.

**Comment by floooh** [comment]
Strange indeed it also breaks in the branch I'm currently working in, and that I just did WebGPU work there not too long ago, currently trying with an older Emscripten SDK, but IIRC I didn't update that for quite a while (currently on 3.1.67).

**Comment by floooh** [comment]
...but ok, Emscripten SDK 3.1.60 works... now bisecting the first version that broke...

**Comment by floooh** [comment]
...there's actually a chanelog note in the upcoming 3.1.69 Emscripten SDK which mentions a fixed WebGPU regression:

https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3169-in-development

**Comment by floooh** [comment]
Yeah, it's this bug, same error messages:

https://github.com/emscripten-core/emscripten/issues/22682

...so the workaround is to either downgrade to Emscripten SDK 3.1.66, or wait for 3.1.68.

With fips you can do:

```
./fips emsdk uninstall
./fips emsdk install 3.1.66
```

**Comment by c1b** [comment]
You are incredible :) 
Thanks for the background info!
