### ISSUE TITLE
Emscripten build issue on Mac

### ISSUE THREAD

**Issue by sy2002** [floooh/sokol-samples#18]
I am running macOs 10.14.2 and XCode 10.1 and python 3.6.5

error "CMake Error at /Users/root/Downloads/floooh/fips/cmake-toolchains/emscripten.toolchain.cmake:32 (message):
  Could not find emscripten SDK! Please run 'fips setup emscripten'!"

How to reproduce:

1. ./fips setup emscripten
2. ./fips set config webgl2-emsc-make-release
3. ./fips build

When executing step #3, the above-mentioned error occurs.

Observation: During the running of step #1, the following errors and warnings are issued, see: [log.txt](https://github.com/floooh/sokol-samples/files/2824674/log.txt)

Could the error message "return subprocess.check_output(['xcrun', '--show-sdk-version']).strip().split('.') 
TypeError: a bytes-like object is required, not 'str'" be related with the fact that I am running **python 3.6.5?**

I don't know if this matters, but I already had emscripten installed via homebrew since a longer time and before running above mentioned steps #1, #2 and #3.

**Comment by floooh** [comment]
Yep, looks like a python3 problem. The error happens in the emscripten SDK's ```emsdk``` script, so not much I can do about it.

For reference, on my system python versions are as follows:
```
> python --version
Python 2.7.15
> python2 --version
Python 2.7.15
> python3 --version
Python 3.7.2
```

**Comment by sy2002** [comment]
I changed my python installation, so that the "python" command now links to python 2.7 instead of 3.6. 

Now, everything works fine.

But it is strange that it did not work in the first place, as googling for "python 3 emscripten" shows, that although there had been problems with python 3 in past, in the meantime, emscripten should be fine with python 3. For example, see here:

https://github.com/emscripten-core/emscripten/pull/5967

Maybe you are still using an older version of emscripten?

Anyway. It works now for me using python 2, so I close this one.

**Comment by floooh** [comment]
> Maybe you are still using an older version of emscripten?

Nope, I'm on the incoming branch, and usually update about once per week. My guess is that emscripten itself is python3-clean, but the ```emsdk``` scripts aren't (technically those don't belong to the emscripten SDK bit are a separate project).
