### ISSUE TITLE
[ERROR] Failed to build config 'd3d11-win64-vstudio-debug' of project 'sokol-samples'

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol-samples#2]
Hello,
I was trying to build Sokol sample on Windows 10 using:
```
fips set config d3d11-win64-vstudio-debug
fips build
```
but have got compiler error:
```
Project "X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\ALL_BUILD.vcxproj" (1) is buildi
ng "X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj" (11) on no
de 1 (default targets).
InitializeBuildStatus:
  Touching "imgui-d3d11.dir\Debug\imgui-d3d11.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX
  86\x64\CL.exe /c /I"x:\GIT\fips-glfw\glfw\include" /I"x:\GIT\fips-imgui\imgui" /Ix:\GIT\sokol\. /
  Zi /nologo /W1 /WX /diagnostics:classic /MP /Od /Oy- /D WIN32 /D _DEBUG /D FIPS_DEBUG=1 /D FIPS_A
  PP_WINDOWED=1 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /MTd /GS /fp:precise /Zc:wchar_t /Z
  c:forScope /Zc:inline /Fo"imgui-d3d11.dir\Debug\\" /Fd"imgui-d3d11.dir\Debug\vc141.pdb" /Gd /TP /
  errorReport:queue "X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc"
  imgui-d3d11.cc
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(32): error C2065: 'ImDrawData': undeclared identifier [X:
\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(32): error C2059: syntax error: ')' [X:\GIT\fips-build\so
kol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(57): error C2065: 'imgui_draw_cb': undeclared identifier
[X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(206): error C2065: 'ImDrawData': undeclared identifier [X
:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(206): error C2065: 'draw_data': undeclared identifier [X:
\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(206): error C2182: 'imgui_draw_cb': illegal use of type '
void' [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\imgui-d3d11.cc(206): error C2448: 'imgui_draw_cb': function-style initia
lizer appears to be a function definition [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debu
g\d3d11\imgui-d3d11.vcxproj]
Done Building Project "X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\imgui-d3d11.
vcxproj" (default targets) -- FAILED.
```
Where is `ImDrawData` supposed to be defined?

**Comment by Oldes** [comment]
I should note, that it is just the `imgui-d3d11.cc` sample which is failing... other samples are OK. Very interesting project btw!

**Comment by floooh** [comment]
Hmm very strange, I cannot reproduce this, both in my existing checkout and a fresh checkout.

ImDrawData should be defined in the imgui.h header which is included here: https://github.com/floooh/sokol-samples/blob/a80b6ccb0d3ed8cf7b3b784d4bcfb92adfdac9d6/d3d11/imgui-d3d11.cc#L12

The file should be at ```../fips-imgui/imgui/imgui.h``` (relative to the sokol-samples directory).

This is in a git submodule via this repo: https://github.com/fungos/fips-imgui, and following the imgui-submodule, the struct is defined here: https://github.com/ocornut/imgui/blob/9912f7eef80a7f8fda21a5c92eb4fcc4e32ee4dd/imgui.h#L1312

Does the GLFW sample have the same problem? (build with config ```win64-vstudio-debug```)

Cheers!
-Floh.

**Comment by Oldes** [comment]
The problem probably is, that I don't have anything like `ImDrawData`  in my `fips-imgui\imgui\imgui.h` file. The version I have (which was downloaded by `fips` is "1.42 wip" , while on the Github is already "v1.53 WIP")

**Comment by Oldes** [comment]
This is the version which is used in current `fips-imgui` repository: https://github.com/ocornut/imgui/blob/d6987d158651dfaea2d05435db4a60306540e588/imgui.h

Updating `imgui` manually does not work as it will give many error even with `fips-imgui` build.

**Comment by Oldes** [comment]
GLFW sample have the same problem because it is trying to use the same older `imgui` library.

**Comment by floooh** [comment]
Strange, on a fresh checkout this shouldn't happen, only when the fips-imgui dependency was fetched a long time ago. 

Can you run a "fips update" from the sokol-samples directory and check if this updates to the proper imgui version? Usually fips will not touch an existing dependency if it sees that the directory exists, only manually through a "fips update".

**Comment by Oldes** [comment]
I just tried to build sokol-samples on OSX and it seems to be working... I will try it again on Windows when I will have some free time again. Maybe the problem is, that I cloned some repositories on Windows manually (not using the `fips` command).

**Comment by Oldes** [comment]
Of course that will be the reason... because on OSX the `fips-imgui` links to `fungos` origin while on Windows I used your (`floooh`) repo.

**Comment by floooh** [comment]
ah ok I see, the fungos version is the definitive one, I only forked this to create pull requests from time to time...
