### ISSUE TITLE
White-space in workspace path breaks in various places....

### ISSUE THREAD

**Issue by olilarkin** [floooh/sokol-samples#24]
C:\Users\Oliver Larkin\Dev\scratch\sokol-samples>fips build
←[93m=== cloning fips build system to 'C:\Users\Oliver Larkin\Dev\scratch/fips':←[0m
Cloning into 'C:\Users\Oliver Larkin\Dev\scratch/fips'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 4159 (delta 79), reused 99 (delta 65), pack-reused 4019
Receiving objects: 100% (4159/4159), 1.49 MiB | 416.00 KiB/s, done.
Resolving deltas: 100% (2839/2839), done.
=== dependency: 'fips-glfw':
Cloning into 'fips-glfw'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 43 (delta 20), reused 41 (delta 19), pack-reused 0
Unpacking objects: 100% (43/43), done.
Submodule 'glfw' (https://github.com/glfw/glfw.git) registered for path 'glfw'
Cloning into 'C:/Users/Oliver Larkin/Dev/scratch/fips-glfw/glfw'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 23550 (delta 32), reused 49 (delta 28), pack-reused 23479
Receiving objects: 100% (23550/23550), 11.77 MiB | 416.00 KiB/s, done.
Resolving deltas: 100% (16490/16490), done.
Submodule path 'glfw': checked out '8055dad7e4d93069a72fdb8abecc131b3c3e5040'
=== dependency: 'fips-libmodplug':
Cloning into 'fips-libmodplug'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
Submodule 'libmodplug' (https://github.com/floooh/libmodplug.git) registered for path 'libmodplug'
Cloning into 'C:/Users/Oliver Larkin/Dev/scratch/fips-libmodplug/libmodplug'...
remote: Enumerating objects: 1049, done.
remote: Total 1049 (delta 0), reused 0 (delta 0), pack-reused 1049
Receiving objects: 100% (1049/1049), 1.40 MiB | 417.00 KiB/s, done.
Resolving deltas: 100% (746/746), done.
Submodule path 'libmodplug': checked out 'c6ae092ab7c24f86920071c3bd6dc5cb5209ffc1'
=== dependency: 'fips-imgui':
Cloning into 'fips-imgui'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 36 (delta 14), reused 33 (delta 11), pack-reused 0
Unpacking objects: 100% (36/36), done.
Submodule 'imgui' (https://github.com/ocornut/imgui.git) registered for path 'imgui'
Cloning into 'C:/Users/Oliver Larkin/Dev/scratch/fips-imgui/imgui'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 28244 (delta 46), reused 55 (delta 40), pack-reused 28161
Receiving objects: 100% (28244/28244), 36.70 MiB | 412.00 KiB/s, done.
Resolving deltas: 100% (20914/20914), done.
Submodule path 'imgui': checked out '8a4422b2fab4ec045ac04ede593845c47601fbb1'
=== dependency: 'sokol':
Cloning into 'sokol'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 48 (delta 24), reused 35 (delta 20), pack-reused 0
Unpacking objects: 100% (48/48), done.
=== building: win64-vstudio-debug
=== generating: win64-vstudio-debug
config file: C:/Users/Oliver Larkin/Dev/scratch/fips/configs/win64-vstudio-debug.yml
cmake -A "x64" -DCMAKE_BUILD_TYPE=Debug -DFIPS_CONFIG=win64-vstudio-debug -DFIPS_USE_CCACHE=OFF -DFIPS_AUTO_IMPORT=OFF -BC:/Users/Oliver Larkin/Dev/scratch/fips-build/sokol-samples/win64-vstudio-debug
 -HC:/Users/Oliver Larkin/Dev/scratch/sokol-samples
CMake Error: The source directory "C:/Users/Oliver Larkin/Dev/scratch/fips-build/sokol-samples/win64-vstudio-debug/Larkin/Dev/scratch/sokol-samples" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[ERROR] Failed to generate 'win64-vstudio-debug' of project 'sokol-samples'

**Comment by floooh** [comment]
Hmm, I guess the space in the directory name could be a problem "C:/Users/Oliver Larkin/"

Fixing this particular case is probably quite simple, but from experience with other command line tools starting to fix "whitespace in paths" will be a rabbit hole. Probably better to work from a directory without spaces.

**Comment by floooh** [comment]
PS: the problem is that wrapping paths with "" or '' via python's subprocess.call() is tricky because depending on operating system and shell, those "" or '' may be removed somewhere between python and the actual shell executing the command.

**Comment by olilarkin** [comment]
thanks, i think i had this exact problem on mac a while ago. moved to a directory without a space and now iit works

**Comment by floooh** [comment]
Ok, I'll keep the bug open and change the name. I did some local fixes (on macOS) and it doesn't seem to be too bad (3 or 4 places for the actual build process, and one for 'fips run'). I might start working on this in a branch, it's not very hight prio ATM though.

**Comment by floooh** [comment]
Hmm, I tinkered around a bit on Windows, and it's quite a mess (e.g. 'cmd /c start "path"' doesn't work at all).

Instead I have added a log warning whenever fips is called and it detects whitespace in the project path. If this is too subtle this could be turned into an error.
