### ISSUE TITLE
small question about correctness

### ISSUE THREAD

**Issue by questor** [floooh/sokol-samples#26]
Hi, sorry to bug you, but I have a small question about correctness in a sample. Currently I've looked at sgl_ortho usage and by looking at the sgl-microui-sapp-sample I have the feeling does your usage works, but only because most matrices are identity ones.
https://github.com/floooh/sokol-samples/blob/master/sapp/sgl-microui-sapp.c#L432
here first sgl_defaults is called and the current matrix-mode is set to modelview, and later in the sample-function you call sgl_ortho without changing the matrix-mode to projection. it works because the other matrices are identity matrices, but the clean solution would be to switch to the projection-matrix and then call sgl_ortho, right?

**Comment by floooh** [comment]
Good catch :) That was indeed an oversight. I've also added a push/pop matrix now, not really necessary, but makes more sense IMHO.

Thanks!
