### ISSUE TITLE
ImGui highdpi demo overlay window example sets wrong window position

### ISSUE THREAD

**Issue by fabiopolimeni** [floooh/sokol-samples#32]
The issue to reproduce is simple. 

Head to https://floooh.github.io/sokol-html5/wasm/imgui-highdpi-sapp.html with a display dpi > 1 (I tested with a 4K with dpi set to 2.5) and from the menu bar Examples->Sample Overlay.
Right click on the overlay window and change to one of the non-default options, such as _Top-Right, Bottom-Left, Bottom-Right_. The overlay window disappears.

What happens is the code will place the overlay window outside the window as if the dpi scaling is not taken into account (that's why the default 0,0 position seems to work properly).

If I divide `window_pos` by `sapp_dpi_scale()` the window is correctly positioned at the corners.

This is the demo code responsible for it. Do you think is a sokol issue or the ImGui demo is not properly written to support high dpi?

```
// Demonstrate creating a simple static window with no decoration + a context-menu to choose which corner of the screen to use.
static void ShowExampleAppSimpleOverlay(bool* p_open)
{
    const float DISTANCE = 10.0f;
    static int corner = 0;
    ImGuiIO& io = ImGui::GetIO();
    if (corner != -1)
    {
        ImVec2 window_pos = ImVec2((corner & 1) ? io.DisplaySize.x - DISTANCE : DISTANCE, (corner & 2) ? io.DisplaySize.y - DISTANCE : DISTANCE);
        ImVec2 window_pos_pivot = ImVec2((corner & 1) ? 1.0f : 0.0f, (corner & 2) ? 1.0f : 0.0f);
        ImGui::SetNextWindowPos(window_pos, ImGuiCond_Always, window_pos_pivot);
    }
    ImGui::SetNextWindowBgAlpha(0.35f); // Transparent background
    if (ImGui::Begin("Example: Simple overlay", p_open, (corner != -1 ? ImGuiWindowFlags_NoMove : 0) | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoFocusOnAppearing | ImGuiWindowFlags_NoNav))
    {
        ImGui::Text("Simple overlay\n" "in the corner of the screen.\n" "(right-click to change position)");
        ImGui::Separator();
        if (ImGui::IsMousePosValid())
            ImGui::Text("Mouse Position: (%.1f,%.1f)", io.MousePos.x, io.MousePos.y);
        else
            ImGui::Text("Mouse Position: <invalid>");
        if (ImGui::BeginPopupContextWindow())
        {
            if (ImGui::MenuItem("Custom",       NULL, corner == -1)) corner = -1;
            if (ImGui::MenuItem("Top-left",     NULL, corner == 0)) corner = 0;
            if (ImGui::MenuItem("Top-right",    NULL, corner == 1)) corner = 1;
            if (ImGui::MenuItem("Bottom-left",  NULL, corner == 2)) corner = 2;
            if (ImGui::MenuItem("Bottom-right", NULL, corner == 3)) corner = 3;
            if (p_open && ImGui::MenuItem("Close")) *p_open = false;
            ImGui::EndPopup();
        }
    }
    ImGui::End();
}
```

**Comment by floooh** [comment]
Hi, is this before or after I committed this fix?

https://github.com/floooh/sokol/commit/fe159f4a37821cb66f8dfed1da51e31800412aff

I noticed the same when opening a centered model dialog box. Instead of in the center, this was placed in the bottom-right corner. The fix I committed should fix that, let me know if it works for you) :)

**Comment by fabiopolimeni** [comment]
Well, if you've committed this fix, only 2 hours ago, I doubt I tested it, but I will :)

In the meantime, it depends on how often WASM examples are updated, this behaviour is reproducible directly from the high-dpi web demo too.

**Comment by floooh** [comment]
Can you check whether it looks right now in the WASM imgui-highdpi-sapp sample? I updated it after I committed the fix (make sure to check with browser-caching disabled, just in case) :)

**Comment by fabiopolimeni** [comment]
It is fixed! Good job!
