### ISSUE TITLE
ImGuiCond_FirstUseEver instead of ImGuiSetCond_FirstUseEver

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol-samples#35]
I'm quite not sure which version of `ImGui` you use by default, but the [current version is using](https://github.com/ocornut/imgui/blob/54c49b5fb1371626f92853a2658cfe2d51d2e41d/imgui.h#L1190):
`ImGuiCond_FirstUseEver` instead of `ImGuiSetCond_FirstUseEver` as used here:
https://github.com/floooh/sokol-samples/blob/491415bbd4e3d0120acbfc11b05b87749715a6e4/sapp/imgui-sapp.cc#L65
and here:
https://github.com/floooh/sokol-samples/blob/491415bbd4e3d0120acbfc11b05b87749715a6e4/sapp/imgui-sapp.cc#L73

**Comment by floooh** [comment]
Thanks for the heads-up, the sokol-samples repo uses some 1.70 WIP version (via https://github.com/fips-libs/fips-imgui), this might be a change in the most recent ImGui version.

I'll fix the samples when I get around updating to the latest ImGui version.

**Comment by floooh** [comment]
...this should be fixed now everywhere, just forgot to close this ticket.
