### ISSUE TITLE
 'vertex_layouts': is not a member of 'sg_pipeline_desc'

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol-samples#5]
It looks that Sokol's `d3d11` samples are now not compatible with recent modifications done in Sokol project itself.
Here is example of errors which are there during build process:
```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX
  86\x64\CL.exe /c /I"x:\GIT\fips-glfw\glfw\include" /I"x:\GIT\fips-imgui\imgui" /Ix:\GIT\sokol /Zi
   /nologo /W1 /WX /diagnostics:classic /MP /Od /Oy- /D WIN32 /D _DEBUG /D FIPS_DEBUG=1 /D FIPS_APP
  _WINDOWED=1 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MTd /GS /fp:precise /Zc:wchar_t /Zc:forSco
  pe /Zc:inline /Fo"triangle-d3d11.dir\Debug\\" /Fd"triangle-d3d11.dir\Debug\vc141.pdb" /Gd /TC /er
  rorReport:queue "X:\GIT\sokol-samples\d3d11\triangle-d3d11.c"
  triangle-d3d11.c
X:\GIT\sokol-samples\d3d11\triangle-d3d11.c(72): error C2039: 'vertex_layouts': is not a member of
'sg_pipeline_desc' [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d11.
vcxproj]
  x:\GIT\sokol\sokol_gfx.h(1368): note: see declaration of 'sg_pipeline_desc'
X:\GIT\sokol-samples\d3d11\triangle-d3d11.c(72): error C2109: subscript requires array or pointer t
ype [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\triangle-d3d11.c(72): error C2224: left of '.stride' must have struct/un
ion type [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\triangle-d3d11.c(72): error C2224: left of '.attrs' must have struct/uni
on type [X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d11.vcxproj]
X:\GIT\sokol-samples\d3d11\triangle-d3d11.c(72): error C2078: too many initializers [X:\GIT\fips-bu
ild\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d11.vcxproj]
Done Building Project "X:\GIT\fips-build\sokol-samples\d3d11-win64-vstudio-debug\d3d11\triangle-d3d
11.vcxproj" (default targets) -- FAILED.
```

PS: `glfw` version is OK.

**Comment by floooh** [comment]
Strange, the D3D11 samples should be fixed with this merge-commit: https://github.com/floooh/sokol-samples/commit/ce2f66fe748384787a897709a94f8714c55e5858

Can you check that you're on the master branch and pulled the latest changes both in the sokol and sokol-samples repository?

I also just tested to build from scratch in a fresh directory:

```
> git clone https://github.com/floooh/sokol-samples
> cd sokol-samples
> fips set config d3d11-win64-vstudio-debug
> fips build
...
> fips list targets
> fips run triangle-d3d11
```

**Comment by Oldes** [comment]
Hm... I deleted folders `fips-build` and `fips-deploy` and it works now... I'm pretty sure I was doing `fips clean`, but it was not enough probably.

**Comment by floooh** [comment]
Ok, I can't think of a reason right now why the compiler wouldn't pick up the changes automatically and rebuild, even without a fips clean (let alone deleting the build folders). I'll try to keep an eye out in case such a problems shows up again. Thanks for the report nonetheless :)

**Comment by Oldes** [comment]
It is quite possible that I was changing the configs and so the `fips clean` was done on different one. Because I can see that  `fips clean` actually deletes content of the `build` and `deploy` for current config - which is exactly what I did manually afterwards.

**Comment by floooh** [comment]
Yeah, "fips clean all" is safer in this case, it deletes all configs in the build- and deploy-dir for one project. Not sure if I mentioned this in the docs (but it's displayed when doing a "fips help clean").
