### ISSUE TITLE
missing http-server referenced by "fips run triangle-emsc"

### ISSUE THREAD

**Issue by datgame** [floooh/sokol-samples#70]
i followed instructions from scratch, i.e. git clone and build.
output from trying emscripten version:
```
=== run 'triangle-emsc' (config: webgl2-emsc-make-release, project: sokol-samples):
'http-server' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "fips", line 17, in <module>
    fips.run(fips_path, proj_path, sys.argv)
  File "d:\otherdev/fips\mod\fips.py", line 51, in run
    verb.verbs[verb_name].run(fips_path, proj_path, verb_args)
  File "d:/otherdev/fips/verbs\run.py", line 28, in run
    retcode = project.run(fips_dir, proj_dir, cfg_name, target_name, target_args, target_cwd)
  File "d:\otherdev/fips\mod\project.py", line 356, in run
    if cmd_line :
UnboundLocalError: local variable 'cmd_line' referenced before assignment
```

**Comment by floooh** [comment]
This is becaused I switched from the python http server to the node.js one (run './fips diag tools' should tell you whether fips can find the node.js http-server). I need to update the readme. Maybe it makes sense to do offer the http-server install step during './fips setup emscripten'...need to think about it...

**Comment by floooh** [comment]
NOTE to self: try installing http-server locally using the node.js versions that's installed as part of the emscripten SDK, that way it wouldn't 'pollute' the system, but everything would stay within the fips-sdk/emsdk directory.

**Comment by floooh** [comment]
...I have improved the error message instead:

```
sokol-samples ➤ ./fips run events-sapp                                                                       git:master
=== run 'events-sapp' (config: sapp-webgl2-wasm-vscode-debug, project: sokol-samples):
[ERROR] http-server tool not found (npm install http-server -g)
sokol-samples ➤
```
