### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by raegnar** [floooh/sokol-samples#76]
Getting "Bad CPU type in executable" when building sokol-samples on an iMac with an Intel Core i5
```
username@iMac sokol-samples % ./fips run quad-metal
=== run 'quad-metal' (config: metal-osx-xcode-debug, project: sokol-samples):
/bin/sh: /Users/username/fips-deploy/sokol-samples/metal-osx-xcode-debug/quad-metal.app/Contents/MacOS/quad-metal: Bad CPU type in executable
```

**Comment by floooh** [comment]
Very strange, what does the 'file' command on the executable say? From within sokol-samples directory:

```
file ../fips-deploy/sokol-samples/metal-osx-xcode-debug/quad-metal.app/Contents/MacOS/quad-metal
```
Should print something like:

```
...Mach-O 64-bit executable x86_64
```

...and otool -h:

```
otool -h ../fips-deploy/sokol-samples/metal-osx-xcode-debug/quad-metal.app/Contents/MacOS/quad-metal
```

...outputs:

```
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           2    26       3304 0x00200085
```

This is on an Intel 13"MBP with Big Sur 11.1 and Xcode 12.2

**Comment by floooh** [comment]
PS: how old is your iMac? It's not a 32-bit system is it?

**Comment by raegnar** [comment]
It looks like somewhere in the toolchain its decided to build this for an arm system because the file command prints 

> `../fips-deploy/sokol-samples/metal-osx-xcode-debug/quad-metal.app/Contents/MacOS/quad-metal: Mach-O 64-bit executable arm64`

also, otool prints

`Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2    26       3384 0x00200085`

and this is not a 32 bit system

**Comment by floooh** [comment]
Hmm very weird indeed. What are your macOS, Xcode and cmake versions?

There's an outdated configuration switch in fips to generate 32-/64-bit universal binaries here:

https://github.com/floooh/fips/blob/ca7883d6e1f440542259b6e0ca18946b76627df5/cmake-toolchains/osx.cmake#L17-L19

But this is skipped by default. It would be surprising if very recent cmake/Xcode versions decide to build ARM executables on an Intel Mac.

**Comment by floooh** [comment]
Ok, fixed. Thanks for the bug report!

**Comment by floooh** [comment]
Ooops, I accidentally set the wrong issue to fixed. Please ignore :)

**Comment by raegnar** [comment]
I am on MacOS 11.0 Big Sur, cmake version 3.17.3, and Xcode 12.0

Can I set that CMAKE_OSX_ARCHITECTURES variable manually in fips?

**Comment by floooh** [comment]
> Can I set that CMAKE_OSX_ARCHITECTURES variable manually in fips?

You could first try setting CMAKE_OSX_ARCHITECTURES at the top of your top-level CMakeLists.txt file, or otherwise you could replace this block here (also remove the "if"):

https://github.com/floooh/fips/blob/master/cmake-toolchains/osx.cmake#L17-L19

**Comment by floooh** [comment]
FYI, while searching for information on why iOS simulator builds are broken in Xcode 12 I stumbled over this cmake issue, which sounds like the problem you're seeing:

https://gitlab.kitware.com/cmake/cmake/-/issues/20893

...so maybe updating to a more recent cmake version will fix the issue.

**Comment by raegnar** [comment]
That did it, I hadn't thought cmake would be the issue as I'm using it extensively in other projects, but updating has fixed the issue here.
