### ISSUE TITLE
Magic number in encodeDepth is not match with referenced article

### ISSUE THREAD

**Issue by eliasku** [floooh/sokol-samples#77]
[Original article](https://aras-p.info/blog/2009/07/30/encoding-floats-to-rgba-the-final/) use multiplier for alpha channel - 16581375. Value 16**0**581375 is used for [Shadows sample](https://github.com/floooh/sokol-samples/blob/master/sapp/shadows-sapp.glsl#L13-L20). Is it typo or on purpose?

**Comment by floooh** [comment]
Good catch, most likely a typo.

**Comment by floooh** [comment]
Ok, fixed in 732d4e871ea9124f46e812ed8c2dd1e6823e5284, thanks for the bug report!
