### ISSUE TITLE
[REQUEST] CMake example project

### ISSUE THREAD

**Issue by raegnar** [floooh/sokol-samples#79]
For those of us who don't want to use another build system (or convince other people to use it), could there be a sample that uses cmake without fips? I have done this partially myself, but it gets really ugly around using sokol-shdc to compile the shaders.

**Comment by floooh** [comment]
Those two projects are standalone projects with simple cmake build files, those projects don't use the shader compiler though:

https://github.com/floooh/cimgui-sokol-starterkit

https://github.com/floooh/pacman.c

Integrating sokol-shdc into cmake would suddenly turn those from fairly simple cmake files into fairly complicated ones (the sokol-tools-bin project must be pulled from github, and sokol-shdc must be integrated as custom build job). IMHO this goes over a "complexity threshold" where those simple example would stop to be useful, especially for people using different build systems than cmake (the current cmake files are simple enough that one can look at them and figure out what compiler settings and system DLLs are needed, in a more complicated cmake file this info would be harder to find).
