### ISSUE TITLE
RasPi 4 sample compile error

### ISSUE THREAD

**Issue by danhambleton** [floooh/sokol-samples#83]
I am trying to compile the raspberry pi sample on a Pi 4. I believe I have installed all the necessary packages etc., however I am getting this error:

```
/usr/bin/ld: CMakeFiles/eval-engine.dir/main.cc.o: in function `_sg_gl_destroy_buffer(_sg_gl_buffer_t*)':
main.cc:(.text+0xe5c): undefined reference to `glDeleteBuffers'
/usr/bin/ld: main.cc:(.text+0x1008): undefined reference to `glDeleteBuffers'
/usr/bin/ld: main.cc:(.text+0x10fc): undefined reference to `glBindBuffer'
/usr/bin/ld: main.cc:(.text+0x1114): undefined reference to `glBindBuffer'
/usr/bin/ld: main.cc:(.text+0x112c): undefined reference to `glBindBuffer'
/usr/bin/ld: main.cc:(.text+0x1144): undefined reference to `glBindBuffer'
```

Has anyone else seen this?

**Comment by danhambleton** [comment]
I should clarify that the above error messages references another codebase, but I get the same error when compiling the sokol raspi sample.

**Comment by floooh** [comment]
Ah sorry, that raspi directory is deceiving, and I really should remove it. I didn't get around adding "official" support to the sokol headers and tools so far (for instance there's also no precompiled shader compiler for the Raspi yet).

**Comment by floooh** [comment]
...PS: the errors themselves look like the program isn't linked with GL (e.g. -lGL is missing).
